version: "3.7"
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - default

volumes:
  mongo-data:

networks:
  default:
    driver: bridge